export enum PrimaryColorScheme {
	NOIR = 'noir',
	EMERALD = 'emerald',
	GREEN = 'green',
	LIME = 'lime',
	ORANGE = 'orange',
	AMBER = 'amber',
	YELLOW = 'yellow',
	TEAL = 'teal',
	CYAN = 'cyan',
	SKY = 'sky',
	BLUE = 'blue',
	INDIGO = 'indigo',
	VIOLET = 'violet',
	PURPLE = 'purple',
	FUCHSIA = 'fuchsia',
	PINK = 'pink',
	ROSE = 'rose',
}
